### ISSUE TITLE
Tracking for full ES6 Module migration and possibly further modularization

### ISSUE THREAD

**Issue by brettz9** [SVG-Edit/svgedit#242]
A major ES6 Module refactoring for our source is ~on the way,~ (*complete*) but a few dependencies are not yet available as ES6 modules (at least without Rollup)

1. [ ] [jQuery](https://github.com/jquery/jquery/wiki/Roadmap) and jQueryUI
1. [ ] jsPDF (at least our version of it); see #51
1. [ ] [MathJax](https://github.com/mathjax/MathJax/issues/1998) (and its dependency TeX-AMS-MML_SVG.js) (Will just need to use [mathjax-v3](https://github.com/mathjax/mathjax-v3/))
1. [ ] [qunit](https://github.com/qunitjs/qunit/issues/1281) (For testing)
1. [x] [sinon](https://github.com/sinonjs/sinon/issues/1805) (Just needs npm bump now) and [sinon-test](https://github.com/sinonjs/sinon-test/issues/93) (For testing)
1. [ ] Once `import()` is widely available, we could avoid loading them via script tag and allow them to simply export an object without needing to import `svg-editor.js` and call `addExtensions`. Currently added an `importModule` polyfill (and `importScript` fallback).
1. [ ] Consider, in place of the embedded API, exporting a module which added *all* dependencies, including jQuery and the default HTML. Have to weigh this with the cost of adding all the default HTML dynamically and whether the styling could support placement elsewhere in the flow of the document. One option might be a syntax which supported Server-side Rendering (so as to minimize initial DOM processing) or to allow pre-compilation to static HTML.
1. [ ] See about spinning off some of the components of the project into their own ES6 Module-friendly npm module

**Comment by jfhenon** [comment]
This issue is not relevant anymore with V7.
