### ISSUE TITLE
A new release

### ISSUE THREAD

**Issue by brettz9** [SVG-Edit/svgedit#258]
The main to-dos now, as I see it, toward a full release are:

- [x] Document the new extension format/locale format (and ideally remove the old canvas docs in favor of jsdoc once more completely applied); other docs. #92; addressed by #264
- [x] Bundle working config file (#151); addressed by #264
- [x] Hosting #43/#171 (May be addressed by #264)
- [x] Make sure cross-domain embedding is working or if browser no longer can support our use case, documented/handled (#173).
- [x] Offer RC version
- [x] Center canvas (#272)
- [x] Fix regression in commit that centered canvas as now storage dialog broken
- [x] Deploy ~(and update #171)~.

**Comment by brettz9** [comment]
3.0.0 is now published! Welcome to give it a whirl!
